name: astra_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  get: 4.6.5
  firebase_auth: ^4.6.1
  firebase_core: 2.13.0
  cloud_firestore: ^4.7.1
  google_fonts: ^4.0.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

 